### ISSUE TITLE
Search: Add Search Bar to the Topic Tool Bar

### ISSUE THREAD

**Issue by alx-zhu** [CMU-313/nodebb-f24-codebb#2]
Acceptance Criteria: Search bar is visible for each category next to the "New Topic" button and users are able to enter inputs.

Dependency: Depends on task 3 with the backend search bar.

**Comment by sherryzhuge1** [comment]
<img width="1461" alt="search" src="https://github.com/user-attachments/assets/77393258-a28b-47b6-9343-60bb7d274846">
