### ISSUE TITLE
UserGuide.Md: Create user guide for using and user testing endorse and search features

### ISSUE THREAD

**Issue by John-Crawshaw** [CMU-313/nodebb-f24-codebb#27]
Create detailed instructions for how to to use and user test endorse and search features with accompanying screenshots/screen recordings.

Estimated Effort: 1 hour
Dependencies: #25, #20, #26 
Acceptance Criteria: The userguide contains detailed instructions, demos, and links to relative tests.

**Comment by Victor-Crawshaw** [comment]
Resolved by PR #28
